[project]
name = "invoice-agent2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.1.0",
    "pywinauto>=0.6.9",
    "pandas>=2.0.0",
    "mt-940>=4.30.0",
]
